language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest
